name: ci
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
env:
  FORCE_COLOR: 3
concurrency:
  group: ${{ github.ref_name }}
  # Only cancel concurrent builds when we are not on the default branch. This
  # way, if a commit breaks the default branch, we can more easily determine
  # which commit caused the failure.
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}
jobs:
  ci:
    name: CI
    if: github.ref_type != 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Prepare
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install
        run: npm clean-install
      - name: Build
        run: npx nr build
      - name: Run Tests
        run: npx nr test.coverage
      - name: Upload Coverage Report
        uses: codecov/codecov-action@v3
